### ISSUE TITLE
Which defconfig is used for image?

### ISSUE THREAD

**Issue by pdp7** [starfive-tech/beaglev_fedora#16]
@tekkamanninja could you link to which defconfig is used?

**Comment by tekkamanninja** [comment]
linux/arch/riscv/configs/starfive_vic7100_evb_sd_net_fedora_defconfig

**Comment by pdp7** [comment]
@tekkamanninja could you also paste link to to dts?

**Comment by pdp7** [comment]
Thank you.  For others viewing this issue:
https://github.com/starfive-tech/beagle_kernel_5.10/blob/starfive/arch/riscv/configs/starfive_vic7100_evb_sd_net_fedora_defconfig

device tree is:
https://github.com/starfive-tech/beagle_uboot-opensbi/blob/starfive/arch/riscv/dts/starfive_vic7100_beagle_v.dts
